const { PrismaClient } = require('../generated/prisma');
const prisma = new PrismaClient();

function randInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}
function pick(arr) { return arr[Math.floor(Math.random()*arr.length)]; }
function randomPhone(){ return `+2659${randInt(10000000,99999999)}` }
function sampleImage(seed){ return `https://images.unsplash.com/photo-${seed}?w=500` }
function randPrice(){ return (randInt(20000, 950000)); }
function randLat(){ return (Math.random() * ( -9.0 - (-17.5) ) + (-17.5)).toFixed(6); }
function randLng(){ return (Math.random() * ( 35.5 - 32.0 ) + 32.0).toFixed(6); }

async function ensureCount(modelName, getCount, createOne) {
  const target = 20;
  let count = await getCount();
  console.log(`${modelName}: current ${count}, target ${target}`);
  let created = 0;
  while (count < target) {
    await createOne(count);
    count++;
    created++;
  }
  console.log(`${modelName}: created ${created} rows`);
}

async function main(){
  await prisma.$connect();

  // Ensure some sellers exist to own shops
  await ensureCount('users', async ()=> await prisma.users.count(), async (i)=>{
    const roles = ['USER','SELLER','USER','SELLER'];
    const role = pick(roles);
    await prisma.users.create({ data: {
      first_name: `Auto${i+1}`,
      last_name: `Generated`,
      email: `autouser${Date.now()}_${i}@example.test`,
      phone_number: randomPhone(),
      password_hash: '$2b$10$TfwMJc7P1CAsukQl/zaIT.Ba67FQUspgkJvtL1WKWWeYVgVXUzGJe',
      role,
      profile_image: sampleImage(1592910147829 + i)
    }});
  });

  // Categories
  await ensureCount('categories', async ()=> await prisma.categories.count(), async (i)=>{
    await prisma.categories.create({ data: {
      name: `Auto Category ${i+1}`,
      description: `Generated category ${i+1}`
    }});
  });

  // Products
  const categories = await prisma.categories.findMany();
  await ensureCount('products', async ()=> await prisma.products.count(), async (i)=>{
    const brand = pick(['Apple','Samsung','Xiaomi','Sony','Huawei','Infinix','Tecno']);
    const cat = pick(categories);
    await prisma.products.create({ data: {
      name: `${brand} Model ${randInt(100,999)} Gen ${randInt(1,5)}`,
      brand,
      description: `Autogenerated product ${i+1}`,
      category_id: cat.id,
      base_price: String(randPrice()),
      images: [sampleImage(1600000000000+i), sampleImage(1600001000000+i)]
    }});
  });

  // Shops
  const sellers = await prisma.users.findMany({ where: { role: 'SELLER' } });
  await ensureCount('shops', async ()=> await prisma.shops.count(), async (i)=>{
    const owner = pick(sellers);
    await prisma.shops.create({ data: {
      name: `Auto Shop ${i+1}`,
      description: `Generated shop ${i+1}`,
      owner_id: owner ? owner.id : sellers[0].id,
      address_line1: `Autogen Address ${i+1}`,
      city: pick(['Lilongwe','Blantyre','Mzuzu','Zomba','Karonga']),
      latitude: randLat(),
      longitude: randLng(),
      phone: randomPhone(),
      email: `shop${Date.now()}_${i}@example.test`,
      is_verified: Math.random() > 0.5,
      delivery_enabled: Math.random() > 0.3,
      logo: sampleImage(1611162617213 + i),
      banner: sampleImage(1498049794561 + i),
      gallery: [sampleImage(1550009158 + i)],
      delivery_methods: ['PICKUP_POINT','COURIER']
    }});
  });

  // Shop products
  const products = await prisma.products.findMany();
  const shops = await prisma.shops.findMany();
  await ensureCount('shop_products', async ()=> await prisma.shop_products.count(), async (i)=>{
    const product = pick(products);
    const shop = pick(shops);
    await prisma.shop_products.create({ data: {
      shop_id: shop.id,
      product_id: product.id,
      price: String(randPrice()),
      stock_quantity: randInt(1,50),
      condition: pick(['NEW','USED','REFURBISHED']),
      shop_description: `Listing ${i+1}`,
      specs: { ram: `${pick([4,6,8,12,16])}GB`, storage: `${pick([64,128,256,512])}GB` },
      images: [sampleImage(1625805866449 + i)],
      is_available: true,
      listing_status: 'LIVE'
    }});
  });

  console.log('All done');
  await prisma.$disconnect();
}

main().catch(e=>{ console.error(e); process.exit(1); });
