const fs = require('fs');
const path = require('path');

const diagram = `flowchart LR
  subgraph Payment Flow
    A[User starts payment (checkout)] -->|initiates| B[PaymentService.initiatePayment]
    B -->|tx_ref| C[PayChangu / Provider]
    C -->|webhook / verify| D[PaymentService.processWebhook / verifyPayment]
  end

  subgraph Order Confirmation
    D -->|PAID| E[PaymentService.confirmPaymentOrders]
    E -->|set order.status=CONFIRMED| F[Order Record]
    F --> G[orderConfirmationService.generateReleaseCode]
    G -->|write release_code & status=PENDING| F
    G --> H[notification.sendReleaseCodeSms]
    H --> I[Buyer receives SMS / email (orderConfirmationTemplate)]
  end

  subgraph Release Verification
    J[Shop / Courier requests verification] --> K[orderConfirmationService.verifyReleaseCode]
    K -->|valid code| L[Credit shop wallet & create transaction]
    L --> M[orders.status = DELIVERED; release_code_status = VERIFIED]
  end

  subgraph Background Jobs
    N[markExpiredPaymentsAsFailed] --> O[restore stock, cancel orders]
    P[processExpiredReleaseCodes] -->|expire| Q[orders.release_code_status = EXPIRED]
  end

  style A fill:#f8f9fa,stroke:#333,stroke-width:1px
  style M fill:#e6ffed,stroke:#2ecc71
`;

const outDir = path.join(__dirname, '..', 'docs');
if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

const mmdPath = path.join(outDir, 'ORDER_CONFIRMATION_FLOW.mmd');
const htmlPath = path.join(outDir, 'ORDER_CONFIRMATION_FLOW.html');

fs.writeFileSync(mmdPath, diagram, 'utf8');

const html = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Order Confirmation Flow</title>
    <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
    <script>mermaid.initialize({ startOnLoad: true });</script>
    <style>body{font-family:Inter,Arial,Helvetica,sans-serif;padding:24px;background:#f7fafc}</style>
  </head>
  <body>
    <h1>Order Confirmation & Notification Flow</h1>
    <div class="mermaid">
${diagram}
    </div>
    <p>Generated by <code>scripts/generate_order_notification_flow.js</code></p>
  </body>
</html>`;

fs.writeFileSync(htmlPath, html, 'utf8');

console.log('Wrote', mmdPath, 'and', htmlPath);

module.exports = { mmdPath, htmlPath };
